<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>kite</AssemblyName>
        <RootNamespace>Kite</RootNamespace>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DefaultItemExcludes>$(DefaultItemExcludes);spike/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Spectre.Console" Version="0.57.2" />
    </ItemGroup>

</Project>